service: service

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: dev
  environment:
    subpingTable: ${self:custom.stage}-subping-core
    authTable: ${self:custom.stage}-subping-auths
    keyTable: ${self:custom.stage}-subping-keys

package:
  individually: true

iamRoleStatements:
  - Effect: "Allow"
    Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem

    Resource:
      Fn::Join:
        - "Fn::GetAtt": [ AuthsTable, Arn ]
        - "Fn::GetAtt": [ SubpingTable, Arn ]
        - "Fn::GetAtt": [ KeyTable, Arn ]

functions:
  currentHotChart:
    handler: ./handler/chart/currentHotChart.handler
    events:
      - http:
          path: currentHotChart
          method: post
          cors: true
          authorizer: aws_iam

  cronMakeRank:
    handler: ./handler/chart/cronMakeRank.handler
    events:
      - schedule: cron(0 21,3,9,15 * * ? *)
  
  getServices:
    handler: ./handler/service/getServices.handler
    events:
      - http:
          path: getServices
          method: post
          cors: true
          authorizer: aws_iam

  getService:
    handler: ./handler/service/getService.handler
    events:
      - http:
          path: getService
          method: post
          cors: true
          authorizer: aws_iam

  getCategories:
    handler: ./handler/category/getCategories.handler
    events:
      - http:
          path: getCategories
          method: get
          cors: true
          authorizer: aws_iam

  makeCategory:
    handler: ./handler/category/makeCategory.handler

  makeService:
    handler: ./handler/service/makeService.handler

  makeServiceCategory:
    handler: ./handler/service/makeServiceCategory.handler

  makeProduct:
    handler: ./handler/product/product.handler

  search:
    handler: ./handler/search/search.handler

  backup:
    handler: ./handler/backup/backup.handler

    getImages:
    handler: ./handler/image/getImages.handler
    events:
      - http:
          path: getImages
          method: post
          cors: true
          authorizer: aws_iam

  saveImage:
    handler: ./handler/image/saveImage.handler

  deleteImage:
    handler: ./handler/image/deleteImage.handler
  # makeReview:
  #   handler: ./handler/review/makeReview.handler
  
